# Generated by Django 5.1.5 on 2025-02-06 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0003_remove_product_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productimg',
            name='image',
        ),
        migrations.RemoveField(
            model_name='productimg',
            name='product',
        ),
        migrations.DeleteModel(
            name='Img',
        ),
        migrations.DeleteModel(
            name='ProductImg',
        ),
    ]
