# Generated by Django 5.1.5 on 2025-02-07 13:43

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0006_comment_rating_delete_favourite'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='media/products/'),
            preserve_default=False,
        ),
    ]
