# Generated by Django 5.1.5 on 2025-02-22 17:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0010_emailconfirmation'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EmailConfirmation',
        ),
    ]
